{
 "title": "Metrics - Rpc",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_memstats_gc_sys_bytes,service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rpc Resp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rpc Resp Count Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job, method) (rate(resp_total{service_name=~\"$job\"}[1m]))",
     "legendFormat": "{{job}} / {{method}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(resp_total{service_name=~\"$job\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rpc Failed Resp Rate % [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service_name, method) (rate(resp_total{status!=\"normal\", service_name=~\"$job\"}[1m])) / sum by(service_name, method) (rate(resp_total{service_name=~\"$job\"}[1m]))",
     "legendFormat": "{{job}} / {{method}}"
    }
   ]
  },
  {
   "title": "Rpc Failed Resp Count Rate [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(job, method) (rate(resp_total{status!=\"normal\", service_name=~\"$job\"}[1m]))",
     "legendFormat": "{{job}} / {{method}}"
    }
   ]
  },
  {
   "title": "Rpc Success Resp Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job, method) (resp_time_sec{quantile=\"0.99\", status=\"normal\", service_name=~\"$job\"}) > 0",
     "legendFormat": "{{job}} / {{method}}"
    }
   ]
  },
  {
   "title": "Rpc Failed Resp Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job, method) (resp_time_sec{quantile=\"0.9\", status!=\"normal\", service_name=~\"$job\"}) > 0",
     "legendFormat": "{{job}} / {{method}}"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (go_memstats_gc_sys_bytes{service_name=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Stack Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service_name, instance) (go_memstats_stack_sys_bytes{service_name=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Reservations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (go_memstats_mspan_sys_bytes{service_name=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: mspan"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}} {{instance}}: mcache"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}} {{instance}}: buck hash"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (go_memstats_heap_sys_bytes{service_name=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: heap reserved"
    },
    {
     "expr": "sum by(job, instance) (go_memstats_heap_inuse_bytes{job=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: heap in use"
    },
    {
     "expr": "sum by(job, instance) (go_memstats_heap_alloc_bytes{job=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: heap alloc"
    },
    {
     "expr": "sum by(job, instance) (go_memstats_heap_idle_bytes{job=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: heap idle"
    },
    {
     "expr": "sum by(job, instance) (go_memstats_heap_released_bytes{job=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: heap released "
    }
   ]
  },
  {
   "title": "Allocation Rate, Bytes",
   "type": "timeseries",
   "description": "Average allocation rate in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (rate(go_memstats_alloc_bytes_total{service_name=~\"$job\"}[1m]))",
     "legendFormat": "{{job}} {{instance}}: bytes malloced/s"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "timeseries",
   "description": "Average rate of heap object allocation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (rate(go_memstats_mallocs_total{service_name=~\"$job\"}[1m]))",
     "legendFormat": "{{job}} {{instance}}: obj mallocs/s"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "Average number of live memory objects",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_name, instance) (go_memstats_mallocs_total{service_name=~\"$job\"}) - go_memstats_frees_total{service_name=~\"$job\"}",
     "legendFormat": "{{job}} {{instance}}: object count"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Average number of goroutines ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service_name, instance) (go_goroutines{service_name=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: goroutine count"
    }
   ]
  },
  {
   "title": "GC min & max duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job, instance) (go_gc_duration_seconds{quantile=\"0\", job=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: min gc time"
    },
    {
     "expr": "sum by(service_name, instance) (go_gc_duration_seconds{quantile=\"1\", service_name=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: max gc time"
    },
    {},
    {}
   ]
  },
  {
   "title": "Next GC, Bytes",
   "type": "timeseries",
   "description": "The number used bytes at which the runtime plans to perform the next GC",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service_name, instance) (go_memstats_next_gc_bytes{service_name=~\"$job\"})",
     "legendFormat": "{{job}} {{instance}}: next gc bytes"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio[5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(label4, input_group) (delta(data_quality{job=~\"$job\", query=\"cache_query\", output_group=\"hit\"}[5m])) / sum by(label4, input_group) (delta(data_quality{job=~\"$job\", query=\"cache_query\"}[5m]))",
     "legendFormat": "{{label4}}/{{input_group}}"
    }
   ]
  },
  {
   "title": "Data Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum by(query, input_group, output_group) (rate(data_quality{job=~\"$job\", query!=\"cache_query\"}[1m]))",
     "legendFormat": "{{query}}: {{input_group}} ~ {{output_group}}"
    }
   ]
  },
  { "title": "For Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } }
 ]
}